# (C) 1997 - 1998 Armin Biere
# $Id: Makefile,v 1.1 2001/11/30 07:54:36 shaleh Exp $

all:
	cd src; make all
test:
	cd src; make test
clean:
	cd src; make clean
install:
	cd src; make install

.PHONY: all test clean install
