# Makefile generated by imake - do not edit!
# $TOG: imake.c /main/97 1997/06/20 20:23:51 kaleb $

# ----------------------------------------------------------------------
# Makefile generated from "Imake.tmpl" and <Imakefile>
# $TOG: Imake.tmpl /main/245 1997/05/20 10:05:47 kaleb $
#
#
#
#
# $XFree86: xc/config/cf/Imake.tmpl,v 3.32.2.8 1998/02/08 11:19:24 dawes Exp $
# ----------------------------------------------------------------------

all::

.SUFFIXES: .i

# $TOG: Imake.cf /main/28 1997/06/25 08:31:36 barstow $
# $XFree86: xc/config/cf/Imake.cf,v 3.34.2.3 1997/07/27 02:41:02 dawes Exp $

# -----------------------------------------------------------------------
# site-specific configuration parameters that need to come before
# the platform-specific parameters - edit site.def to change

# site:  $XConsortium: site.def /main/revisionist/4 1996/12/31 08:02:07 kaleb $
# site:  $XFree86: xc/config/cf/site.def,v 3.17.2.1 1997/06/22 10:32:21 dawes Exp $

# $XFree86: xc/config/cf/xf86site.def,v 3.101.2.15 1998/02/24 19:05:42 hohndel Exp $

# ----------------------------------------------------------------------
# platform-specific configuration parameters - edit linux.cf to change

# platform:  $TOG: linux.cf /main/36 1997/06/16 22:21:03 kaleb $
# platform:  $XFree86: xc/config/cf/linux.cf,v 3.57.2.12 1998/03/01 01:57:10 dawes Exp $

# operating system:  Linux 2.1.91 i586 [ELF] (2.1.91)
# libc:	(6.0.6)
# binutils:	(28)

# $XConsortium: lnxLib.rules /main/13 1996/09/28 16:11:01 rws $
# $XFree86: xc/config/cf/lnxLib.rules,v 3.28.2.3 1997/06/22 10:32:20 dawes Exp $

# $XFree86: xc/config/cf/xfree86.cf,v 3.129.2.22 1998/02/24 19:05:43 hohndel Exp $

# $XConsortium: xfree86.cf /main/34 1996/12/06 11:45:18 rws $

LINKKITDIR = $(USRLIBDIR)/Server
XF98LINKKITDIR = $(USRLIBDIR)/Server

       XF86SRC = $(SERVERSRC)/hw/xfree86
  XF86ACCELSRC = $(XF86SRC)/accel
    XF86COMSRC = $(XF86SRC)/common
 XF86CONFIGSRC = $(XF86COMSRC)
     XF86HWSRC = $(XF86SRC)/common_hw
     XF86OSSRC = $(XF86SRC)/os-support
  VGADRIVERSRC = $(XF86SRC)/vga256/drivers
VGA16DRIVERSRC = $(XF86SRC)/vga16/drivers
 VGA2DRIVERSRC = $(XF86SRC)/vga2/drivers
 MONODRIVERSRC = $(XF86SRC)/mono/drivers
   S3DRIVERSRC = $(XF86SRC)/accel/s3/drivers
  S3VDRIVERSRC = $(XF86SRC)/accel/s3_virge/drivers

       XF68SRC = $(SERVERSRC)/hw/xfree68
    XF68COMSRC = $(XF68SRC)/common
 XF68CONFIGSRC = $(XF68COMSRC)
     XF68OSSRC = $(XF68SRC)/os-support

           XF98SRC = $(SERVERSRC)/hw/xfree98
      XF98ACCELSRC = $(XF98SRC)/accel
        XF98COMSRC = $(XF98SRC)/common
     XF98CONFIGSRC = $(XF98COMSRC)
         XF98HWSRC = $(XF98SRC)/common_hw/generic
      XF98HWNECSRC = $(XF98SRC)/common_hw/nec
    XF98HWPWSKBSRC = $(XF98SRC)/common_hw/pwskb
     XF98HWPWLBSRC = $(XF98SRC)/common_hw/pwlb
    XF98HWGA968SRC = $(XF98SRC)/common_hw/ga968
         XF98OSSRC = $(XF98SRC)/os-support
  XF98VGADRIVERSRC = $(XF98SRC)/vga256/drivers
XF98VGA16DRIVERSRC = $(XF98SRC)/vga16/drivers
 XF98VGA2DRIVERSRC = $(XF98SRC)/vga2/drivers
 XF98MONODRIVERSRC = $(XF98SRC)/mono/drivers
XF98NECS3DRIVERSRC = $(XF98SRC)/accel/s3nec/drivers
XF98PWSKBDRIVERSRC = $(XF98SRC)/accel/s3pwskb/drivers
 XF98PWLBDRIVERSRC = $(XF98SRC)/accel/s3pwlb/drivers
XF98GA968DRIVERSRC = $(XF98SRC)/accel/s3ga968/drivers

        XFREE86DOCDIR = $(LIBDIR)/doc
      XFREE86PSDOCDIR = $(XFREE86DOCDIR)/PostScript
    XFREE86HTMLDOCDIR = $(XFREE86DOCDIR)/html
XFREE86JAPANESEDOCDIR = $(XFREE86DOCDIR)/Japanese

# $XConsortium: xf86.rules /main/9 1996/10/31 14:54:26 kaleb $
# $XFree86: xc/config/cf/xf86.rules,v 3.16.2.1 1997/05/18 12:00:01 dawes Exp $

# ----------------------------------------------------------------------
# site-specific configuration parameters that go after
# the platform-specific parameters - edit site.def to change

# site:  $XConsortium: site.def /main/revisionist/4 1996/12/31 08:02:07 kaleb $
# site:  $XFree86: xc/config/cf/site.def,v 3.17.2.1 1997/06/22 10:32:21 dawes Exp $

# ---------------------------------------------------------------------
# Imake rules for building libraries, programs, scripts, and data files
# rules:  $TOG: Imake.rules /main/222 1997/07/17 20:04:40 kaleb $
# rules:  $XFree86: xc/config/cf/Imake.rules,v 3.33.2.7 1998/02/06 09:02:17 dawes Exp $

 _NULLCMD_ = @ echo -n

TKLIBNAME =

TKLIBDIR =

TCLLIBNAME =

TCLIBDIR =

          PATHSEP = /
            SHELL = /bin/sh

              TOP = .
      CURRENT_DIR = .

            IMAKE = imake
           DEPEND = gccmakedep
        MKDIRHIER = mkdir -p
    EXPORTLISTGEN =
        CONFIGSRC = $(TOP)/config
         IMAKESRC = $(CONFIGSRC)/imake
        DEPENDSRC = $(CONFIGSRC)/util

          INCROOT = /usr/X11R6.3/include
        USRLIBDIR = /usr/X11R6.3/lib
        VARLIBDIR = /var/lib
         SHLIBDIR = /usr/X11R6.3/lib
       LINTLIBDIR = $(USRLIBDIR)/lint
          MANPATH = /usr/X11R6.3/man
    MANSOURCEPATH = $(MANPATH)/man
           MANDIR = $(MANSOURCEPATH)1
        LIBMANDIR = $(MANSOURCEPATH)3
       FILEMANDIR = $(MANSOURCEPATH)5

               AR = ar clq
  BOOTSTRAPCFLAGS =
               CC = gcc
               AS = as

.SUFFIXES: .cc

              CXX = gcc
          CXXFILT = c++filt
           CXXLIB =
    CXXDEBUGFLAGS = -O2 -ffast-math -finline-functions -fno-strength-reduce -m486 -malign-loops=2 -malign-jumps=2 -malign-functions=2
CXXDEPENDINCLUDES =
 CXXEXTRA_DEFINES =
CXXEXTRA_INCLUDES =
   CXXSTD_DEFINES = -Dlinux -D__i386__ -D_POSIX_C_SOURCE=199309L -D_POSIX_SOURCE -D_XOPEN_SOURCE=500L -D_BSD_SOURCE -D_SVID_SOURCE $(CXXPROJECT_DEFINES)
       CXXOPTIONS =
      CXXINCLUDES = $(INCLUDES) $(TOP_INCLUDES) $(CXXEXTRA_INCLUDES)
       CXXDEFINES = $(CXXINCLUDES) $(CXXSTD_DEFINES) $(THREADS_CXXDEFINES) $(CXXEXTRA_DEFINES) $(DEFINES)
         CXXFLAGS = $(CXXDEBUGFLAGS) $(CXXOPTIONS) $(THREADS_CXXFLAGS) $(CXXDEFINES)

         COMPRESS = compress
          GZIPCMD = gzip
              CPP = /lib/cpp $(STD_CPP_DEFINES)
    PREPROCESSCMD = gcc -E $(STD_CPP_DEFINES)
          INSTALL = install
     INSTALLFLAGS = -c
               LD = ld
              LEX = flex -l
           LEXLIB = -lfl
             YACC = bison -y
           CCYACC = bison -y
             LINT = lint
      LINTLIBFLAG = -C
         LINTOPTS = -axz
               LN = ln -s
             MAKE = make
               MV = mv -f
               CP = cp

           RANLIB = ranlib
  RANLIBINSTFLAGS =

               RM = rm -f
        MANSUFFIX = 1x
     LIBMANSUFFIX = 3x
    FILEMANSUFFIX = 5x
            TROFF = psroff
            NROFF = nroff
         MSMACROS = -ms
        MANMACROS = -man
              TBL = tbl
              EQN = eqn
             NEQN = neqn
              COL = col

            DVIPS = dvips
            LATEX = latex

     STD_INCLUDES =
  STD_CPP_DEFINES = -traditional -Dlinux -D__i386__ -D_POSIX_C_SOURCE=199309L -D_POSIX_SOURCE -D_XOPEN_SOURCE=500L -D_BSD_SOURCE -D_SVID_SOURCE $(PROJECT_DEFINES)
      STD_DEFINES = -Dlinux -D__i386__ -D_POSIX_C_SOURCE=199309L -D_POSIX_SOURCE -D_XOPEN_SOURCE=500L -D_BSD_SOURCE -D_SVID_SOURCE $(PROJECT_DEFINES)
 EXTRA_LOAD_FLAGS =
  EXTRA_LDOPTIONS =
  EXTRA_LIBRARIES =
             TAGS = ctags

   PARALLELMFLAGS =

    SHAREDCODEDEF =
         SHLIBDEF =

     SHLIBLDFLAGS = -shared

         PICFLAGS = -fPIC

      CXXPICFLAGS = -fPIC

    PROTO_DEFINES = -DFUNCPROTO=15 -DNARROWPROTO

     INSTPGMFLAGS = -s

     INSTBINFLAGS = -m 0755
     INSTUIDFLAGS = -m 4711
     INSTLIBFLAGS = -m 0644
     INSTINCFLAGS = -m 0444
     INSTMANFLAGS = -m 0444
     INSTDATFLAGS = -m 0444
    INSTKMEMFLAGS = -m 4711

      PROJECTROOT = /usr/X11R6.3

      CDEBUGFLAGS = -O2 -ffast-math -finline-functions -fno-strength-reduce -m486 -malign-loops=2 -malign-jumps=2 -malign-functions=2
        CCOPTIONS =

      ALLINCLUDES = $(INCLUDES) $(EXTRA_INCLUDES) $(TOP_INCLUDES) $(STD_INCLUDES)
       ALLDEFINES = $(ALLINCLUDES) $(STD_DEFINES) $(EXTRA_DEFINES) $(PROTO_DEFINES) $(THREADS_DEFINES) $(DEFINES)
           CFLAGS = $(CDEBUGFLAGS) $(CCOPTIONS) $(THREADS_CFLAGS) $(ALLDEFINES)
        LINTFLAGS = $(LINTOPTS) -DLINT $(ALLDEFINES) $(DEPEND_DEFINES)
         LDPRELIB = -L$(USRLIBDIR)
        LDPOSTLIB =
        LDOPTIONS = $(CDEBUGFLAGS) $(CCOPTIONS)  $(EXTRA_LDOPTIONS) $(THREADS_LDFLAGS) $(LOCAL_LDFLAGS) $(LDPRELIBS)
     CXXLDOPTIONS = $(CXXDEBUGFLAGS) $(CXXOPTIONS) $(EXTRA_LDOPTIONS) $(THREADS_CXXLDFLAGS) $(LOCAL_LDFLAGS) $(LDPRELIBS)

           LDLIBS = $(LDPOSTLIBS) $(THREADS_LIBS) $(SYS_LIBRARIES) $(EXTRA_LIBRARIES)

           CCLINK = $(CC)

          CXXLINK = $(CXX)

     LDSTRIPFLAGS = -x
   LDCOMBINEFLAGS = -r
      DEPENDFLAGS =

# Not sure this belongs here
         TKLIBDIR =
         TKINCDIR =
        TKLIBNAME =
        TKLIBRARY = -L$(TKLIBDIR) -l$(TKLIBNAME)
        TCLLIBDIR =
        TCLINCDIR =
       TCLLIBNAME =
       TCLLIBRARY = -L$(TCLLIBDIR) -l$(TCLLIBNAME)

        MACROFILE = linux.cf
           RM_CMD = $(RM)

    IMAKE_DEFINES =

         IRULESRC = $(CONFIGDIR)
        IMAKE_CMD = $(IMAKE) -DUseInstalled -I$(IRULESRC) $(IMAKE_DEFINES)

     ICONFIGFILES = $(IRULESRC)/Imake.tmpl $(IRULESRC)/X11.tmpl 			$(IRULESRC)/site.def $(IRULESRC)/$(MACROFILE) 			$(IRULESRC)/xfree86.cf $(IRULESRC)/xf86.rules $(IRULESRC)/xf86site.def $(IRULESRC)/host.def $(EXTRA_ICONFIGFILES)

# $TOG: X11.rules /main/4 1997/04/30 15:23:24 kaleb $

# ----------------------------------------------------------------------
# X Window System Build Parameters and Rules
# $TOG: X11.tmpl /main/292 1997/05/20 10:05:59 kaleb $
#
#
#
#
# $XFree86: xc/config/cf/X11.tmpl,v 1.8.2.4 1998/01/23 12:35:08 dawes Exp $

# -----------------------------------------------------------------------
# X Window System make variables; these need to be coordinated with rules

             XTOP = $(TOP)
           BINDIR = /usr/X11R6.3/bin
     BUILDINCROOT = $(TOP)/exports
      BUILDINCDIR = $(BUILDINCROOT)/include
      BUILDINCTOP = ../..
      BUILDLIBDIR = $(TOP)/exports/lib
      BUILDLIBTOP = ../..
      BUILDBINDIR = $(TOP)/exports/bin
      BUILDBINTOP = ../..
    XBUILDINCROOT = $(XTOP)/exports
     XBUILDINCDIR = $(XBUILDINCROOT)/include/X11
     XBUILDINCTOP = ../../..
     XBUILDBINDIR = $(XBUILDINCROOT)/bin
           INCDIR = $(INCROOT)
           ADMDIR = /usr/adm
           LIBDIR = $(USRLIBDIR)/X11
   TOP_X_INCLUDES = -I$(XPROJECTROOT)/include

           VARDIR = /var/X11

          FONTDIR = $(LIBDIR)/fonts
         XINITDIR = $(LIBDIR)/xinit
           XDMDIR = $(LIBDIR)/xdm
        XDMVARDIR = $(VARLIBDIR)/xdm
           TWMDIR = $(LIBDIR)/twm
           XSMDIR = $(LIBDIR)/xsm
           NLSDIR = $(LIBDIR)/nls
       XLOCALEDIR = $(LIBDIR)/locale
        PEXAPIDIR = $(LIBDIR)/PEX
      LBXPROXYDIR = $(LIBDIR)/lbxproxy
  PROXYMANAGERDIR = $(LIBDIR)/proxymngr
        XPRINTDIR = $(LIBDIR)
      XAPPLOADDIR = $(LIBDIR)/app-defaults
       FONTCFLAGS = -t

     INSTAPPFLAGS = $(INSTDATFLAGS)

              RGB = rgb
            FONTC = bdftopcf
        MKFONTDIR = mkfontdir

       DOCUTILSRC = $(XTOP)/doc/util
        CLIENTSRC = $(TOP)/clients
          DEMOSRC = $(TOP)/demos
       XDOCMACROS = $(DOCUTILSRC)/macros.t
       XIDXMACROS = $(DOCUTILSRC)/indexmacros.t
       PROGRAMSRC = $(TOP)/programs
           LIBSRC = $(XTOP)/lib
          FONTSRC = $(XTOP)/fonts
       INCLUDESRC = $(BUILDINCROOT)/include
      XINCLUDESRC = $(INCLUDESRC)/X11
        SERVERSRC = $(XTOP)/programs/Xserver
       CONTRIBSRC = $(XTOP)/../contrib
   UNSUPPORTEDSRC = $(XTOP)/unsupported
           DOCSRC = $(XTOP)/doc
           RGBSRC = $(XTOP)/programs/rgb
      BDFTOPCFSRC = $(PROGRAMSRC)/bdftopcf
     MKFONTDIRSRC = $(PROGRAMSRC)/mkfontdir
    FONTSERVERSRC = $(PROGRAMSRC)/xfs
       FONTINCSRC = $(XTOP)/include/fonts
        EXTINCSRC = $(XTOP)/include/extensions
     TRANSCOMMSRC = $(LIBSRC)/xtrans
   TRANS_INCLUDES = -I$(TRANSCOMMSRC)

       XENVLIBDIR = $(USRLIBDIR)
   CLIENTENVSETUP = LD_LIBRARY_PATH=$(XENVLIBDIR)

# $XConsortium: lnxLib.tmpl,v 1.5 95/01/11 21:44:44 kaleb Exp $
# $XFree86: xc/config/cf/lnxLib.tmpl,v 3.9 1996/02/24 04:32:52 dawes Exp $

          XLIBSRC = $(LIBSRC)/X11

SOXLIBREV = 6.1
DEPXONLYLIB =
XONLYLIB =  -lX11

LINTXONLY = $(LINTLIBDIR)/llib-lX11.ln

         XLIBONLY = $(XONLYLIB)

      XEXTLIBSRC = $(LIBSRC)/Xext

SOXEXTREV = 6.3
DEPEXTENSIONLIB =
EXTENSIONLIB =  -lXext

LINTEXTENSION = $(LINTLIBDIR)/llib-lXext.ln

LINTEXTENSIONLIB = $(LINTEXTENSION)
          DEPXLIB = $(DEPEXTENSIONLIB) $(DEPXONLYLIB)
             XLIB = $(EXTENSIONLIB) $(XONLYLIB)
         LINTXLIB = $(LINTXONLYLIB)

    XSSLIBSRC = $(LIBSRC)/Xss

DEPXSSLIB = $(USRLIBDIR)/libXss.a
XSSLIB =  -lXss

LINTXSS = $(LINTLIBDIR)/llib-lXss.ln

    XXF86MISCLIBSRC = $(LIBSRC)/Xxf86misc

DEPXXF86MISCLIB = $(USRLIBDIR)/libXxf86misc.a
XXF86MISCLIB =  -lXxf86misc

LINTXXF86MISC = $(LINTLIBDIR)/llib-lXxf86misc.ln

    XXF86VMLIBSRC = $(LIBSRC)/Xxf86vm

DEPXXF86VMLIB = $(USRLIBDIR)/libXxf86vm.a
XXF86VMLIB =  -lXxf86vm

LINTXXF86VM = $(LINTLIBDIR)/llib-lXxf86vm.ln

    XXF86DGALIBSRC = $(LIBSRC)/Xxf86dga

DEPXXF86DGALIB = $(USRLIBDIR)/libXxf86dga.a
XXF86DGALIB =  -lXxf86dga

LINTXXF86DGA = $(LINTLIBDIR)/llib-lXxf86dga.ln

    XDPMSLIBSRC = $(LIBSRC)/Xdpms

DEPXDPMSLIB = $(USRLIBDIR)/libXdpms.a
XDPMSLIB =  -lXdpms

LINTXDPMS = $(LINTLIBDIR)/llib-lXdpms.ln

         XAUTHSRC = $(LIBSRC)/Xau

DEPXAUTHLIB = $(USRLIBDIR)/libXau.a
XAUTHLIB =  -lXau

LINTXAUTH = $(LINTLIBDIR)/llib-lXau.ln

      XDMCPLIBSRC = $(LIBSRC)/Xdmcp

DEPXDMCPLIB = $(USRLIBDIR)/libXdmcp.a
XDMCPLIB =  -lXdmcp

LINTXDMCP = $(LINTLIBDIR)/llib-lXdmcp.ln

           XMUSRC = $(LIBSRC)/Xmu

SOXMUREV = 6.0
DEPXMULIB =
XMULIB =  -lXmu

LINTXMU = $(LINTLIBDIR)/llib-lXmu.ln

       OLDXLIBSRC = $(LIBSRC)/oldX

DEPOLDXLIB = $(USRLIBDIR)/liboldX.a
OLDXLIB =  -loldX

LINTOLDX = $(LINTLIBDIR)/llib-loldX.ln

         XPLIBSRC = $(LIBSRC)/Xp

SOXPREV = 6.2
DEPXPLIB =
XPLIB =  -lXp

LINTXP = $(LINTLIBDIR)/llib-lXp.ln

       TOOLKITSRC = $(LIBSRC)/Xt

SOXTREV = 6.0
DEPXTOOLONLYLIB =
XTOOLONLYLIB =  -lXt

LINTXTOOLONLY = $(LINTLIBDIR)/llib-lXt.ln

      DEPXTOOLLIB = $(DEPXTOOLONLYLIB) $(DEPSMLIB) $(DEPICELIB)
         XTOOLLIB = $(XTOOLONLYLIB) $(SMLIB) $(ICELIB)
     LINTXTOOLLIB = $(LINTXTOOLONLYLIB)

       XALIBSRC = $(LIBSRC)/Xa

SOXAREV = 1.0
DEPXALIB =
XALIB =  -lXa

LINTXA = $(LINTLIBDIR)/llib-lXa.ln

       AWIDGETSRC = $(LIBSRC)/Xaw

SOXAWREV = 6.1
DEPXAWLIB =
XAWLIB =  -lXaw

LINTXAW = $(LINTLIBDIR)/llib-lXaw.ln

         XILIBSRC = $(LIBSRC)/Xi

SOXINPUTREV = 6.0
DEPXILIB =
XILIB =  -lXi

LINTXI = $(LINTLIBDIR)/llib-lXi.ln

      XTESTLIBSRC = $(LIBSRC)/Xtst

SOXTESTREV = 6.1
DEPXTESTLIB =
XTESTLIB =  -lXtst

LINTXTEST = $(LINTLIBDIR)/llib-lXtst.ln

        PEXLIBSRC = $(LIBSRC)/PEX5

SOPEXREV = 6.0
DEPPEXLIB =
PEXLIB =  -lPEX5

LINTPEX = $(LINTLIBDIR)/llib-lPEX5.ln

        XIELIBSRC = $(LIBSRC)/XIE

SOXIEREV = 6.0
DEPXIELIB =
XIELIB =  -lXIE

LINTXIE = $(LINTLIBDIR)/llib-lXIE.ln

      PHIGSLIBSRC = $(LIBSRC)/PHIGS

DEPPHIGSLIB = $(USRLIBDIR)/libphigs.a
PHIGSLIB =  -lphigs

LINTPHIGS = $(LINTLIBDIR)/llib-lphigs.ln

DEPXBSDLIB = $(USRLIBDIR)/libXbsd.a
XBSDLIB =  -lXbsd

LINTXBSD = $(LINTLIBDIR)/llib-lXbsd.ln

           ICESRC = $(LIBSRC)/ICE

SOICEREV = 6.3
DEPICELIB =
ICELIB =  -lICE

LINTICE = $(LINTLIBDIR)/llib-lICE.ln

            SMSRC = $(LIBSRC)/SM

SOSMREV = 6.0
DEPSMLIB =
SMLIB =  -lSM

LINTSM = $(LINTLIBDIR)/llib-lSM.ln

           XKEYSRC = $(LIBSRC)/Xkey

SOXKEYREV = 6.0
DEPXKEYLIB =
XKEYLIB =  -lXkey

LINTXKEY = $(LINTLIBDIR)/llib-lXkey.ln

         FSLIBSRC = $(LIBSRC)/FS

DEPFSLIB = $(USRLIBDIR)/libFS.a
FSLIB =  -lFS

LINTFS = $(LINTLIBDIR)/llib-lFS.ln

         FONTLIBSRC = $(LIBSRC)/font

DEPFONTLIB = $(USRLIBDIR)/libfont.a
FONTLIB =  -lfont

LINTFONT = $(LINTLIBDIR)/llib-lfont.ln

          XPMLIBSRC = $(LIBSRC)/Xpm

DEPXPMLIB = $(USRLIBDIR)/libXpm.a
XPMLIB =  -lXpm

LINTXPM = $(LINTLIBDIR)/llib-lXpm.ln

    XKBFILELIBSRC = $(LIBSRC)/xkbfile

DEPXKBFILELIB = $(USRLIBDIR)/libxkbfile.a
XKBFILELIB =  -lxkbfile

LINTXKBFILE = $(LINTLIBDIR)/llib-lxkbfile.ln

     XKBCOMPCMD = xkbcomp

    XKBUILIBSRC = $(LIBSRC)/xkbui

DEPXKBUILIB = $(USRLIBDIR)/libxkbui.a
XKBUILIB =  -lxkbui

LINTXKBUI = $(LINTLIBDIR)/llib-lxkbui.ln

          DEPLIBS = $(DEPXAWLIB) $(DEPXMULIB) $(DEPXTOOLLIB) $(DEPXLIB)

         DEPLIBS1 = $(DEPLIBS)
         DEPLIBS2 = $(DEPLIBS)
         DEPLIBS3 = $(DEPLIBS)
         DEPLIBS4 = $(DEPLIBS)
         DEPLIBS5 = $(DEPLIBS)
         DEPLIBS6 = $(DEPLIBS)
         DEPLIBS7 = $(DEPLIBS)
         DEPLIBS8 = $(DEPLIBS)
         DEPLIBS9 = $(DEPLIBS)
         DEPLIBS10 = $(DEPLIBS)

XMULIBONLY = -lXmu
XMULIB = $(XMULIBONLY) $(XTOOLLIB) $(XLIB)

        CONFIGDIR = $(LIBDIR)/config

    USRLIBDIRPATH = $(USRLIBDIR)
        LDPRELIBS = -L$(USRLIBDIR)
       LDPOSTLIBS =
     TOP_INCLUDES = -I$(INCROOT) $(TOP_X_INCLUDES)
  PROJECT_DEFINES =

CXXPROJECT_DEFINES =

# ----------------------------------------------------------------------
# start of Imakefile

# Imakefile / Makefile for Blackbox - an X11 Window manager
# Copyright (c) 1997, 1998 by Brad Hughes, bhughes@arn.net
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# (See the included file COPYING / GPL-2.0)

# Source files from which blackbox is built

Includes =		blackbox.hh graphics.hh icon.hh llist.hh menu.hh session.hh window.hh workspace.hh
Sources =		blackbox.cc graphics.cc icon.cc llist.cc main.cc menu.cc session.cc sessionmenu.cc window.cc windowmenu.cc workspace.cc workspacemenu.cc
Objects =		blackbox.o graphics.o icon.o main.o menu.o llist.o session.o sessionmenu.o window.o windowmenu.o workspace.o workspacemenu.o

# Add compiler options here
CompileOptimize =	$(CXXFLAGS)
CompileOptions =	-Wall -W -DSHAPE $(CompileOptimize)

DefaultsPath =		-DXAPPLOADDIR=\"$(XAPPLOADDIR)\" -DXLIBDIR=\"$(LIBDIR)\"
Libraries =		$(XLIB) $(EXTENSIONLIB)
OtherLibs =

PROGRAMS = blackbox
SRCS1 = $(Sources)
OBJS1 = $(Objects)

 OBJS = $(OBJS1) $(OBJS2) $(OBJS3) $(OBJS4) $(OBJS5) \
 $(OBJS6) $(OBJS7) $(OBJS8) $(OBJS9) $(OBJS10)
 SRCS = $(SRCS1) $(SRCS2) $(SRCS3) $(SRCS4) $(SRCS5) \
 $(SRCS6) $(SRCS7) $(SRCS8) $(SRCS9) $(SRCS10)

all:: $(PROGRAMS)

blackbox: $(OBJS1) $(DEPLIBS1)
	$(RM) $@
	$(CCLINK) -o $@ $(LDOPTIONS) $(OBJS1)  $(Libraries) $(LDLIBS)  $(OtherLibs) $(EXTRA_LOAD_FLAGS)

install:: blackbox
	@if [ -d $(DESTDIR)$(BINDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(BINDIR)); fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTPGMFLAGS)  blackbox $(DESTDIR)$(BINDIR)/blackbox

install.man:: blackbox.man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTMANFLAGS) blackbox.man $(DESTDIR)$(MANDIR)/blackbox.$(MANSUFFIX)

depend::
	$(DEPEND) $(DEPENDFLAGS) -- $(ALLDEFINES) $(DEPEND_DEFINES) -- $(SRCS)

lint:
	$(LINT) $(LINTFLAGS) $(SRCS) $(LINTLIBS)
lint1:
	$(LINT) $(LINTFLAGS) $(FILE) $(LINTLIBS)

clean::
	$(RM) $(PROGRAMS)

.cc.o: $(Sources)
	$(CXX) $(CompileOptions) -c -o $@ $<

session.o: session.cc
	$(CXX) $(CompileOptions) $(DefaultsPath) -c -o $@ $<

#  %%% *** %%% *** Do not edit the lines below *** %%% *** %%%

depend::
	rm -f Makefile.bak

install:: install.app-defaults
install.app-defaults::
	@if [ ! -d $(XAPPLOADDIR) ]; then 		$(MKDIRHIER) $(XAPPLOADDIR); 	fi

	$(INSTALL) $(INSTALLFLAGS) $(INSTMANFLAGS) Blackbox.ad $(XAPPLOADDIR)/Blackbox.ad
	$(INSTALL) $(INSTALLFLAGS) $(INSTMANFLAGS) Menu.ad $(LIBDIR)/BlackboxMenu.ad

# Make rules I enjoy

distclean::
	make clean
	rm -f Makefile

new::
	make clean
	make all

dist::
	make distclean
	xmkmf -a
	make all

# ----------------------------------------------------------------------
# common rules for all Makefiles - do not edit

.c.i:
	$(RM) $@
	 $(CC) -E $(CFLAGS) $(_NOOP_) $*.c > $@

emptyrule::

clean::
	$(RM) *.CKP *.ln *.BAK *.bak *.o core errs ,* *~ *.a .emacs_* tags TAGS make.log MakeOut  "#"*

Makefile::
	-@if [ -f Makefile ]; then set -x; \
	$(RM) Makefile.bak; $(MV) Makefile Makefile.bak; \
	else exit 0; fi
	$(IMAKE_CMD) -DTOPDIR=$(TOP) -DCURDIR=$(CURRENT_DIR)

tags::
	$(TAGS) -w *.[ch]
	$(TAGS) -xw *.[ch] > TAGS

man_keywords::

# ----------------------------------------------------------------------
# empty rules for directories that do not have SUBDIRS - do not edit

install::
	@echo "install in $(CURRENT_DIR) done"

install.man::
	@echo "install.man in $(CURRENT_DIR) done"

install.linkkit::
	@echo "install.linkkit in $(CURRENT_DIR) done"

Makefiles::

includes::

depend::

# ----------------------------------------------------------------------
# dependencies generated by makedepend

# DO NOT DELETE
blackbox.o: blackbox.cc blackbox.hh /usr/X11R6.3/include/X11/Xlib.h \
 /usr/include/sys/types.h /usr/local/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/include/gnu/types.h /usr/include/time.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stddef.h \
 /usr/include/endian.h /usr/include/bytesex.h \
 /usr/include/sys/select.h /usr/include/selectbits.h \
 /usr/X11R6.3/include/X11/X.h /usr/X11R6.3/include/X11/Xfuncproto.h \
 /usr/X11R6.3/include/X11/Xosdefs.h llist.hh session.hh \
 /usr/X11R6.3/include/X11/Xutil.h /usr/X11R6.3/include/X11/Xresource.h \
 /usr/include/stdio.h /usr/include/libio.h /usr/include/_G_config.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stdarg.h \
 /usr/include/stdio_lim.h menu.hh graphics.hh /usr/include/signal.h \
 /usr/include/sigset.h /usr/include/signum.h /usr/include/sigaction.h \
 /usr/include/sigcontext.h /usr/include/asm/sigcontext.h \
 /usr/include/stdlib.h /usr/include/alloca.h /usr/include/unistd.h \
 /usr/include/posix_opt.h /usr/include/confname.h
graphics.o: graphics.cc graphics.hh /usr/X11R6.3/include/X11/Xlib.h \
 /usr/include/sys/types.h /usr/local/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/include/gnu/types.h /usr/include/time.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stddef.h \
 /usr/include/endian.h /usr/include/bytesex.h \
 /usr/include/sys/select.h /usr/include/selectbits.h \
 /usr/X11R6.3/include/X11/X.h /usr/X11R6.3/include/X11/Xfuncproto.h \
 /usr/X11R6.3/include/X11/Xosdefs.h session.hh \
 /usr/X11R6.3/include/X11/Xutil.h /usr/X11R6.3/include/X11/Xresource.h \
 /usr/include/stdio.h /usr/include/libio.h /usr/include/_G_config.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stdarg.h \
 /usr/include/stdio_lim.h llist.hh menu.hh
icon.o: icon.cc window.hh menu.hh /usr/X11R6.3/include/X11/Xlib.h \
 /usr/include/sys/types.h /usr/local/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/include/gnu/types.h /usr/include/time.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stddef.h \
 /usr/include/endian.h /usr/include/bytesex.h \
 /usr/include/sys/select.h /usr/include/selectbits.h \
 /usr/X11R6.3/include/X11/X.h /usr/X11R6.3/include/X11/Xfuncproto.h \
 /usr/X11R6.3/include/X11/Xosdefs.h llist.hh workspace.hh icon.hh \
 session.hh /usr/X11R6.3/include/X11/Xutil.h \
 /usr/X11R6.3/include/X11/Xresource.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stdarg.h \
 /usr/include/stdio_lim.h graphics.hh
llist.o: llist.cc llist.hh /usr/include/stdio.h /usr/include/libio.h \
 /usr/local/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/gnu/stubs.h /usr/include/_G_config.h \
 /usr/include/gnu/types.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stddef.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stdarg.h \
 /usr/include/stdio_lim.h
main.o: main.cc blackbox.hh /usr/X11R6.3/include/X11/Xlib.h \
 /usr/include/sys/types.h /usr/local/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/include/gnu/types.h /usr/include/time.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stddef.h \
 /usr/include/endian.h /usr/include/bytesex.h \
 /usr/include/sys/select.h /usr/include/selectbits.h \
 /usr/X11R6.3/include/X11/X.h /usr/X11R6.3/include/X11/Xfuncproto.h \
 /usr/X11R6.3/include/X11/Xosdefs.h llist.hh
menu.o: menu.cc menu.hh /usr/X11R6.3/include/X11/Xlib.h \
 /usr/include/sys/types.h /usr/local/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/include/gnu/types.h /usr/include/time.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stddef.h \
 /usr/include/endian.h /usr/include/bytesex.h \
 /usr/include/sys/select.h /usr/include/selectbits.h \
 /usr/X11R6.3/include/X11/X.h /usr/X11R6.3/include/X11/Xfuncproto.h \
 /usr/X11R6.3/include/X11/Xosdefs.h llist.hh graphics.hh session.hh \
 /usr/X11R6.3/include/X11/Xutil.h /usr/X11R6.3/include/X11/Xresource.h \
 /usr/include/stdio.h /usr/include/libio.h /usr/include/_G_config.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stdarg.h \
 /usr/include/stdio_lim.h
session.o: session.cc session.hh /usr/X11R6.3/include/X11/Xlib.h \
 /usr/include/sys/types.h /usr/local/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/include/gnu/types.h /usr/include/time.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stddef.h \
 /usr/include/endian.h /usr/include/bytesex.h \
 /usr/include/sys/select.h /usr/include/selectbits.h \
 /usr/X11R6.3/include/X11/X.h /usr/X11R6.3/include/X11/Xfuncproto.h \
 /usr/X11R6.3/include/X11/Xosdefs.h /usr/X11R6.3/include/X11/Xutil.h \
 /usr/X11R6.3/include/X11/Xresource.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stdarg.h \
 /usr/include/stdio_lim.h llist.hh menu.hh graphics.hh window.hh \
 workspace.hh icon.hh blackbox.hh /usr/X11R6.3/include/X11/Xatom.h \
 /usr/X11R6.3/include/X11/cursorfont.h \
 /usr/X11R6.3/include/X11/keysym.h \
 /usr/X11R6.3/include/X11/keysymdef.h /usr/include/string.h \
 /usr/include/sys/time.h /usr/include/timebits.h
sessionmenu.o: sessionmenu.cc blackbox.hh \
 /usr/X11R6.3/include/X11/Xlib.h /usr/include/sys/types.h \
 /usr/local/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/gnu/stubs.h /usr/include/gnu/types.h /usr/include/time.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stddef.h \
 /usr/include/endian.h /usr/include/bytesex.h \
 /usr/include/sys/select.h /usr/include/selectbits.h \
 /usr/X11R6.3/include/X11/X.h /usr/X11R6.3/include/X11/Xfuncproto.h \
 /usr/X11R6.3/include/X11/Xosdefs.h llist.hh session.hh \
 /usr/X11R6.3/include/X11/Xutil.h /usr/X11R6.3/include/X11/Xresource.h \
 /usr/include/stdio.h /usr/include/libio.h /usr/include/_G_config.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stdarg.h \
 /usr/include/stdio_lim.h menu.hh graphics.hh /usr/include/stdlib.h \
 /usr/include/alloca.h /usr/include/string.h
window.o: window.cc window.hh menu.hh /usr/X11R6.3/include/X11/Xlib.h \
 /usr/include/sys/types.h /usr/local/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/include/gnu/types.h /usr/include/time.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stddef.h \
 /usr/include/endian.h /usr/include/bytesex.h \
 /usr/include/sys/select.h /usr/include/selectbits.h \
 /usr/X11R6.3/include/X11/X.h /usr/X11R6.3/include/X11/Xfuncproto.h \
 /usr/X11R6.3/include/X11/Xosdefs.h llist.hh workspace.hh icon.hh \
 session.hh /usr/X11R6.3/include/X11/Xutil.h \
 /usr/X11R6.3/include/X11/Xresource.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stdarg.h \
 /usr/include/stdio_lim.h graphics.hh /usr/X11R6.3/include/X11/Xatom.h \
 /usr/X11R6.3/include/X11/keysym.h \
 /usr/X11R6.3/include/X11/keysymdef.h /usr/include/string.h
windowmenu.o: windowmenu.cc window.hh menu.hh \
 /usr/X11R6.3/include/X11/Xlib.h /usr/include/sys/types.h \
 /usr/local/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/gnu/stubs.h /usr/include/gnu/types.h /usr/include/time.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stddef.h \
 /usr/include/endian.h /usr/include/bytesex.h \
 /usr/include/sys/select.h /usr/include/selectbits.h \
 /usr/X11R6.3/include/X11/X.h /usr/X11R6.3/include/X11/Xfuncproto.h \
 /usr/X11R6.3/include/X11/Xosdefs.h llist.hh workspace.hh icon.hh \
 session.hh /usr/X11R6.3/include/X11/Xutil.h \
 /usr/X11R6.3/include/X11/Xresource.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stdarg.h \
 /usr/include/stdio_lim.h graphics.hh
workspace.o: workspace.cc workspace.hh /usr/X11R6.3/include/X11/Xlib.h \
 /usr/include/sys/types.h /usr/local/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/include/gnu/types.h /usr/include/time.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stddef.h \
 /usr/include/endian.h /usr/include/bytesex.h \
 /usr/include/sys/select.h /usr/include/selectbits.h \
 /usr/X11R6.3/include/X11/X.h /usr/X11R6.3/include/X11/Xfuncproto.h \
 /usr/X11R6.3/include/X11/Xosdefs.h menu.hh llist.hh icon.hh \
 session.hh /usr/X11R6.3/include/X11/Xutil.h \
 /usr/X11R6.3/include/X11/Xresource.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stdarg.h \
 /usr/include/stdio_lim.h graphics.hh window.hh \
 /usr/include/sys/time.h /usr/include/timebits.h
workspacemenu.o: workspacemenu.cc workspace.hh \
 /usr/X11R6.3/include/X11/Xlib.h /usr/include/sys/types.h \
 /usr/local/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/gnu/stubs.h /usr/include/gnu/types.h /usr/include/time.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stddef.h \
 /usr/include/endian.h /usr/include/bytesex.h \
 /usr/include/sys/select.h /usr/include/selectbits.h \
 /usr/X11R6.3/include/X11/X.h /usr/X11R6.3/include/X11/Xfuncproto.h \
 /usr/X11R6.3/include/X11/Xosdefs.h menu.hh llist.hh icon.hh \
 session.hh /usr/X11R6.3/include/X11/Xutil.h \
 /usr/X11R6.3/include/X11/Xresource.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.3/include/stdarg.h \
 /usr/include/stdio_lim.h graphics.hh window.hh
