.\"
.\" Man page for Bsetroot
.\"
.\" Copyright (c) 2000 by Wilbert Berendsen <wbsoft@xs4all.nl>
.\"
.TH bsetroot 1 "June 16th, 2000" "0.60.3"
.SH 名前
bsetroot \- blackbox の壁紙設定用のユーティリティ
.SH 書式
.BR bsetroot " \-help"
.br
.B bsetroot
.RI "[ \-display " display " ] \-solid " color
.br
.B bsetroot
.RI "[ \-display " display " ] \-mod " "x y" " \-fg " color " \-bg " color
.br
.B bsetroot
.RI "[ \-display " display " ] \-gradient " texture " \-from " color " \-to " color
.SH 説明
bsetroot は、単一色あるいは二つの色の組み合わせで塗り潰し、二つの異なる色を
べースにしたグラデーションテキスチャという、三つのやりかたで壁紙を設定できる
ユーティリティです。
.PP
bsetroot は
.IR xsetroot (1)
に似た機能を持っていますが、複数ディスプレイへの描画や Blackbox と同じ
方法でのグラデーションテクスチャをサポートしています。
カーソルは未サポートです。
bsetroot は blackbox パッケージの一部です。
.SH オプション
三種類のやりかたがあるので、まずその内のどれであるか選択しなければなりません:
.TP
.BI \-solid " 色"
指定した色でルートウィンドウを塗り潰します。
.TP
.BI \-mod " x y"
色の組み合わせパターンをつくります。必ず
.BR \-bg " と " \-fg
を指定する必要があります。
.TP
.BI \-gradient " テクスチャ文字列"
指定したテクスチャをルートウィンドウに描画します。可能なテクスチャ文字列に
ついては
.IR blackbox (1)
を参照して下さい。
また
.BR \-from " と " \-to
も指定しなければなりません。
.TP
.BI \-display " ディスプレイ"
bsetroot に指定したディスプレイに接続するように指示します。
.TP
.BI "\-bg, \-background " color
背景色。
.B \-mod
パターンで必要です。
.TP
.BI "\-fg, \-foreground " color
前景色。
.B \-mod
パターンで必要です。
.TP
.BI \-from " color"
テクスチャの開始色。
.B \-gradient
オプションで必要です。
.TP
.BI \-to " color"
テクスチャの終了色。
.B \-gradient
オプションで必要です。
.TP
.B \-help
バージョン情報と簡単なヘルプを表示します。
.SH 作者
bsetroot は最所 Brad Hughes
.nh \" hyphenation off
(blackbox@alug.org)
.hy \" on again
と Jeff Raven
.nh
(jraven@psu.edu)によって書かれ、保守されていましたが、
.hy
今は Sean 'Shaleh' Perry
.nh
(shaleh@debian.org) と
.hy
他の世界中からのたくさんの開発者からの改良、貢献によって成り立っています。
.hy
.SH 関連項目
.IR blackbox (1)
